---
gui:
  nerdFontsVersion: '3'
  showRandomTip: false
  showBranchCommitHash: false
  showCommandLog: true
  spinner:
    frames: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']
    rate: 120
git:
  fetchAll: true
  autoFetch: true
  mainBranches:
    - main
    - master
  pagers:
      - externalDiffCommand: difft --color=always --display=inline
refresher:
  refreshInterval: 10
  fetchInterval: 30
