---
gui:
  nerdFontsVersion: '3'
  showBranchCommitHash: true
  showCommandLog: true
  spinner:
    frames: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']
    rate: 60
git:
  pagers:
      - externalDiffCommand: difft --color=always --display=inline
