---
gui:
  nerdFontsVersion: '3'
  showBranchCommitHash: true
  showCommandLog: true
  spinner:
    frames: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']
    rate: 60
git:
  pagers:
    - pager: diff-so-fancy
